# .github/workflows/check-aws.yml
name: AWS Connection Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  AWS_REGION: "eu-west-2"

jobs:
  ping-aws:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::738158818734:role/terraform-cicd-github-oidc-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Show caller identity
        run: |
          echo "If this prints an ARN, creds are good:"
          aws sts get-caller-identity

      - name: List S3 buckets
        run: aws s3 ls
